version: "3.9"
services:
  db:
    image: postgres:13    
    restart: always
    env_file:
      - ./app/.env 
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
  app:
      build: app
      expose:
        - "8000" 
      volumes:      
        - static_volume:/opt/app/static
      env_file:
        - ./app/.env
      depends_on:
        - db
  nginx:
    image: nginx:latest
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/nginx/conf.d:/etc/nginx/conf.d
      - ./app/data:/app/data/      
      - static_volume:/opt/app/static
    depends_on:
      - app
    ports:
      - "8000:80"

volumes:
  postgres_data:
  static_volume: